// Created by TraceCompiler1.1.6
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TACTILEFEEDBACKRESOLVERTRACES_H__
#define __TACTILEFEEDBACKRESOLVERTRACES_H__

#define KOstTraceComponentID 0x2000b494

#define TACTILE_RESOLVER_PLAY_FEEDBACK_1 0x400001
#define TACTILE_RESOLVER_PLAY_FEEDBACK_0 0x400002


#endif

// End of file

