// Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// apaflrec.cpp
//

#include <f32file.h>
#include <apaflrec.h>
#include <apaid.h>
#include <apacmdln.h>
#include "APASTD.H"
#include "APGCLI.H"
#include <ecom/ecom.h>

//
// MApaAppStarter
//

/** Constructor for MApaAppStarter. */
EXPORT_C MApaAppStarter::MApaAppStarter()
	{
	}

/** Reserved for future use */
EXPORT_C void MApaAppStarter::MApaAppStarter_Reserved1()
	{
	}
	
/** Reserved for future use */
EXPORT_C void MApaAppStarter::MApaAppStarter_Reserved2()
	{
	}
