// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __THUMBNAILMEMORYCARDOBSERVERTRACES_H__
#define __THUMBNAILMEMORYCARDOBSERVERTRACES_H__

#define KOstTraceComponentID 0x102830ab

#define CTHUMBNAILMEMORYCARDOBSERVER_CTHUMBNAILMEMORYCARDOBSERVER 0x860046
#define DUP1_CTHUMBNAILMEMORYCARDOBSERVER_CTHUMBNAILMEMORYCARDOBSERVER 0x860047
#define CTHUMBNAILMEMORYCARDOBSERVER_RUNL 0x860048
#define CTHUMBNAILMEMORYCARDOBSERVER_STARTNOTIFY 0x860049


#endif

// End of file

