// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __THUMBNAILDISKUNMOUNTOBSERVERTRACES_H__
#define __THUMBNAILDISKUNMOUNTOBSERVERTRACES_H__

#define KOstTraceComponentID 0x102830ab

#define DUP1_CTHUMBNAILDISKUNMOUNTOBSERVER_CTHUMBNAILDISKUNMOUNTOBSERVER 0x86000b
#define CTHUMBNAILDISKUNMOUNTOBSERVER_CTHUMBNAILDISKUNMOUNTOBSERVER 0x86000c
#define CTHUMBNAILDISKUNMOUNTOBSERVER_RUNL 0x86000d
#define CTHUMBNAILDISKUNMOUNTOBSERVER_STARTNOTIFY 0x86000e


#endif

// End of file

