// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TMFORMATOBSERVERTRACES_H__
#define __TMFORMATOBSERVERTRACES_H__

#define KOstTraceComponentID 0x102830ab

#define CTMFORMATOBSERVER_CTMFORMATOBSERVER 0x8601d6
#define CTMFORMATOBSERVER_CONSTRUCTL 0x8601d7
#define CTMFORMATOBSERVER_POLLSTATUS 0x8601d8
#define CTMFORMATOBSERVER_HANDLEBACKUPOPERATIONEVENTL 0x8601d9


#endif

// End of file

