// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TMSHUTDOWNOBSERVERTRACES_H__
#define __TMSHUTDOWNOBSERVERTRACES_H__

#define KOstTraceComponentID 0x102830ab

#define CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8601da
#define DUP1_CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8601db
#define DUP2_CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8601dc
#define DUP3_CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8601dd
#define CTMSHUTDOWNOBSERVER_CTMSHUTDOWNOBSERVER 0x8601de
#define CTMSHUTDOWNOBSERVER_RUNL 0x8601df
#define DUP1_CTMSHUTDOWNOBSERVER_RUNL 0x8601e0
#define CTMSHUTDOWNOBSERVER_DOCANCEL 0x8601e1


#endif

// End of file

