// Created by TraceCompiler1.1.6
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TACTICONHAPTICSPLAYERTRACES_H__
#define __TACTICONHAPTICSPLAYERTRACES_H__

#define KOstTraceComponentID 0x2001fe52

#define TACTICON_HAPTICS_PLAYER_PLAY_TACTICON_1 0x400001
#define TACTICON_HAPTICS_PLAYER_PLAY_TACTICON_0 0x400002
#define TACTICON_HAPTICS_PLAYER_STOP_TACTICON_1 0x400003
#define TACTICON_HAPTICS_PLAYER_STOP_TACTICON_0 0x400004


#endif

// End of file

