/*
* Copyright (c) 2002-2004 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  ?Description
*
*/


// Autogenerated from \epoc32\build\generated\Xml\DrmRel1_0StringDict00AttributeValueTable.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_DrmRel1_0StringDict00AttributeValueTable
#define STRINGTABLE_DrmRel1_0StringDict00AttributeValueTable

#include "stringpool.h"

struct TStringTable;

/** A String table */
class DrmRel1_0StringDict00AttributeValueTable
    {
public:
    enum TStrings
        {
        /**  */
        EXmlnsOEx,
        /**  */
        EXmlnsODd,
        /**  */
        EXmlnsDs,
        /** http://odrl.net/1.1/ODRL-EX */
        EOdrlEx,
        /** http://odrl.net/1.1/ODRL-DD */
        EOdrlDd,
        /** http://www.w3.org/2000/09/xmldsig/ */
        EXmlDsig
        };
    static const TStringTable Table;
    };

#endif // STRINGTABLE_DrmRel1_0StringDict00AttributeValueTable

