/*
* Copyright (c) 2002-2004 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  ?Description
*
*/



// Autogenerated from \epoc32\build\generated\Xml\DrmRel1_0StringDict00TagTable.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_DrmRel1_0StringDict00TagTable
#define STRINGTABLE_DrmRel1_0StringDict00TagTable

#include "stringpool.h"

struct TStringTable;

/** A String table */
class DrmRel1_0StringDict00TagTable
    {
public:
    enum TStrings
        {
        // Element names
        // CodePage 00
        /** rights */
        ERights,
        /** context */
        EContext,
        /** version */
        EVersion,
        /** uid */
        EUid,
        /** agreement */
        EAgreement,
        /** asset */
        EAsset,
        /** KeyInfo */
        EKeyInfo,
        /** KeyValue */
        EKeyValue,
        /** permission */
        EPermission,
        /** play */
        EPlay,
        /** display */
        EDisplay,
        /** execute */
        EExecute,
        /** print */
        EPrint,
        /** constraint */
        EConstraint,
        /** count */
        ECount,
        /** datetime */
        EDateTime,
        /** start */
        EStart,
        /** end */
        EEnd,
        /** interval */
        EInterval,
        /** -//OMA//DTD DRMREL 1.0//EN */
        EUri,
        /** 14~0 */
        EPublicId,
        /** -//OMA//DTD DRMREL 1.0//EN~0 */
        EFormalPublicId
        };
    static const TStringTable Table;
    };

#endif // STRINGTABLE_DrmRel1_0StringDict00TagTable

