// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PREFIX RUN_UTILS
// Remove the RSC file
// In fact all these tests do not care about the APC settings
MakeReadWrite c:\Private\101F5027\AlarmServer.rsc
DeleteFile c:\Private\101F5027\AlarmServer.rsc
REMOVE_PREFIX
RUN_SCRIPT \testdata\scripts\TEAlarmServer_man_exceptTC3.script

RUN_SCRIPT \testdata\scripts\TEAlarmServer_man_TC3.script
