// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE alarmserverunittestserver

START_TESTCASE PIM-UCT-PREQ1118-APC-AS-0012
//! @SYMTestCaseID PIM-UCT-PREQ1118-APC-AS-0012
//! @SYMTestCaseDesc Default hard-coded APC settings
//! @SYMFssID <App-Services>/<AlarmServer>/EAS.001
//! @SYMTestStatus Implemented
//! @SYMTestPriority High
//! @SYMTestActions Remove AlarmServer resource file from the private folder of the AlarmServer, if present. Remove alarmserver.ini file, if present. Startup the AlarmServer. Verify that APC settings of the AlarmServer are the default hardcoded settings.
//! @SYMTestExpectedResults when neither .ini file, nor resource file supplied, the AlarmServer should start with the default hardcoded settings.
//! @SYMTestType CT

PREFIX RUN_UTILS
// Remove the INI file
MakeReadWrite c:\Private\101F5027\AlarmServer.ini
DeleteFile c:\Private\101F5027\AlarmServer.ini
REMOVE_PREFIX

RUN_TEST_STEP 180 alarmserverunittestserver AlarmPlayConfig \testdata\config\TEAlarmServer_apc.ini hardcoded
END_TESTCASE PIM-CT-PREQ1118-APC-AS-0012

