// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE alarmserverunittestserver

START_TESTCASE PIM-UCT-PREQ1118-APC-AS-0022
//! @SYMTestCaseID PIM-UCT-PREQ1118-APC-AS-0022
//! @SYMTestCaseDesc Last Entry Repeat option
//! @SYMFssID <App-Services>/<AlarmServer>/EAS.002
//! @SYMTestStatus Implemented
//! @SYMTestPriority High
//! @SYMTestActions Use Resource file with RepeatSetting=RepeatLast. Start the AlarmServer. Add an alarm, enable and wait for expiry. Verify that after the sequence end is reached the last interval and duration replayed continually.
//! @SYMTestExpectedResults Last interval and duration shall be replayed continually.
//! @SYMTestType CT
PREFIX RUN_UTILS
// Remove the INI file
MakeReadWrite c:\Private\101F5027\AlarmServer.ini
DeleteFile c:\Private\101F5027\AlarmServer.ini
REMOVE_PREFIX
RUN_TEST_STEP 360 alarmserverunittestserver AlarmPlayConfig \testdata\config\TEAlarmServer_apc.ini repeatlast
END_TESTCASE PIM-UCT-PREQ1118-APC-AS-0022

