// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE alarmserverunittestserver

START_TESTCASE PIM-UCT-PREQ1118-APC-AS-0013
//! @SYMTestCaseID PIM-UCT-PREQ1118-APC-AS-0013
//! @SYMTestCaseDesc .ini file overrides settings in the resource file 
//! @SYMFssID <App-Services>/<AlarmServer>/EAS.001
//! @SYMTestStatus Implemented
//! @SYMTestPriority High
//! @SYMTestActions Place a compiled Resource file in the private folder of the AlarmServer. Make sure there is no .ini file in the folder. Startup the AlarmServer. Stop the AlarmServer: backup .ini file is created. Replace the Resource file with a Resource file containing different settings. Start the AlarmServer. Verify APC settings read at startup.
//! @SYMTestExpectedResults AlarmServer should receive settings from the .ini file
//! @SYMTestType CT

PREFIX RUN_UTILS
// Remove the INI file
MakeReadWrite c:\Private\101F5027\AlarmServer.ini
DeleteFile c:\Private\101F5027\AlarmServer.ini
REMOVE_PREFIX
RUN_TEST_STEP 10 alarmserverunittestserver APCSetIntervals \testdata\config\TEAlarmServer_apc.ini set
RUN_TEST_STEP 120 alarmserverunittestserver AlarmPlayConfig \testdata\config\TEAlarmServer_apc.ini set
START_TESTCASE PIM-UCT-PREQ1118-APC-AS-0013
