// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE alarmserverunittestserver

START_TESTCASE PIM-UCT-PREQ1118-APC-AS-0052
//! @SYMTestCaseID PIM-UCT-PREQ1118-APC-AS-0052
//! @SYMTestCaseDesc Incorrect intervals 
//! @SYMFssID <App-Services>/<AlarmServer>/EAS.001
//! @SYMTestStatus Implemented
//! @SYMTestPriority High
//! @SYMTestActions Use Resource file contained invalid intervals. Start the AlarmServer. Add an alarm, enable and wait for expiry. Verify that AlarmServer handles the situation properly (i.e. is not hanging up, nor panics badly).
//! @SYMTestExpectedResults any inconsistencies and errors in the resource file shall be handled with no harm to the AlarmServer, Alert Server or any other component involved.
//! @SYMTestType CT
PREFIX RUN_UTILS

// Remove the INI file
MakeReadWrite c:\Private\101F5027\AlarmServer.ini
DeleteFile c:\Private\101F5027\AlarmServer.ini
REMOVE_PREFIX
RUN_TEST_STEP 10 alarmserverunittestserver AlarmPlayConfig \testdata\config\TEAlarmServer_apc.ini hardcoded

PREFIX RUN_UTILS
// Remove the INI file
MakeReadWrite c:\Private\101F5027\AlarmServer.ini
DeleteFile c:\Private\101F5027\AlarmServer.ini
REMOVE_PREFIX
RUN_TEST_STEP 10 alarmserverunittestserver APCSetIntervals \testdata\config\TEAlarmServer_apc.ini disable-config

END_TESTCASE PIM-UCT-PREQ1118-APC-AS-0052
