//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestCaseID		API-APPFWK-VIEWSRV-0001
//! @SYMTestCaseDesc 		Ensure ViewServer responds with permission denied for test server without the correct capabilities.
//! @SYMTestPriority 		High
//! @SYMTestStatus 		3. Released
//! @SYMTestActions  		Connect to ViewServer and check whether test server process
//!  				has the permission to access the mentioned apis
//!  				API Calls:		
//!  				CVwsSessionWrapper::NewL();
//!  				CVwsSessionWrapper::SetSystemDefaultView(const TVwsViewId &aViewId);
//!  				CVwsSessionWrapper::SetClientRequestTimeOut(TTimeIntervalMicroSeconds32 aDuration);
//!  				CVwsSessionWrapper::SetServerEventTimeOut(TTimeIntervalMicroSeconds32 aDuration);
//!  				CVwsSessionWrapper::EnableServerEventTimeOut(TBool aEnable);
//!  				CVwsSessionWrapper::ShutdownViewServer();
//! @SYMTestExpectedResults 	Test should complete without any panic.The called API's should return KErrPermissionDenied.

START_TESTCASE API-APPFWK-VIEWSRV-0001

PRINT Run Capability1 Viewsrv test
//
PRINT INFO: Set test server capability to NULL (00000000)
RUN_PROGRAM -1 setcap appfwk_viewsrv_test_server.exe 00000000 appfwk_viewsrv_test_server0000.exe
PRINT INFO: Test Server capability now set to NULL (00000000)  
//
LOAD_SUITE appfwk_viewsrv_test_server0000
RUN_TEST_STEP 100 appfwk_viewsrv_test_server0000 Capability1

END_TESTCASE API-APPFWK-VIEWSRV-0001
