// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// which do not take a TRequestStatus.
// Use the CApStarter::StartL() function which do not take a TRequestStatus 
// to load TestApp. Verify that the application has been loaded.
// 
//

//! @file
//! @SYMTestCaseID		API-APPFWK-APSTART-0001
//! @SYMPREQ			PREQ1089 PREQ1871
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus		3. Released
//! @SYMTestCaseDesc		Check if an application can be loaded with the StartApp method 
//! @SYMTestActions		Load apstart.dll dynamically and create an object for CAppStart. 
//! @SYMTestExpectedResults 	Application should be started with no errors.


START_TESTCASE API-APPFWK-APSTART-0001

PRINT Run ApStart tests
LOAD_SUITE tapstart_server

RUN_TEST_STEP 100 tapstart_server CApStartTestStep

END_TESTCASE API-APPFWK-APSTART-0001
