//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE Cap_Te_Cap_SipServer_sc
//
PRINT Run Te_Cap_SipServer at 00000020
PRINT 
//

HEAP_MARK
RUN_TEST_STEP 100 Cap_Te_Cap_SipServer_sc CESipItcSetAppUid1Step
TEST_COMPLETE
HEAP_MARKEND
UNLOAD
