// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Call CancelStart().
// 
//

//! @file
//! @SYMTestCaseID 		API-APPFWK-AMA-0001
//! @SYMTestCaseDesc		Cancel a pending asynchronous StartL() request.
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9141
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		3. Released
//! @SYMTestCaseDependencies	The appropriate database has been created.
//! @SYMTestActions		Call asynchronous StartL() with a DSC that takes a long time to complete execution.
//! @SYMTestExpectedResults 	The request status for the StartL() call will have the value KErrCancel.

PRINT Run AmaStarterCancel tests

LOAD_SUITE tamastarter_server

START_TESTCASE API-APPFWK-AMA-0001
RUN_TEST_STEP 100 tamastarter_server AmaStarterCancel
END_TESTCASE API-APPFWK-AMA-0001
