// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestCaseID 		API-APPFWK-AMASTARTER-0009
//! @SYMPREQ 			PREQ871
//! @SYMREQ			REQ9141
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		3. Released
//! @SYMTestCaseDependencies	The SID of the launching server has to ve different to KSysStartSID
//! @SYMTestCaseDesc		Ensuring SID check
//! @SYMTestActions		Launch the AMAstarer with application with invalid SID.
//! @SYMTestExpectedResults 	AMAStarter should leave with Error.

PRINT Run AmaStarterInvalidSID tests

LOAD_SUITE tamastarter_server

START_TESTCASE API-APPFWK-AMASTARTER-0009
RUN_TEST_STEP 100 tamastarter_server AmaStarterInvalidSID
END_TESTCASE API-APPFWK-AMASTARTER-0009
