// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __THUMBNAILIMAGEPROVIDERTRACES_H__
#define __THUMBNAILIMAGEPROVIDERTRACES_H__

#define KOstTraceComponentID 0x102830ac

#define CTHUMBNAILIMAGEPROVIDER_CTHUMBNAILIMAGEPROVIDER 0x860035
#define DUP1_CTHUMBNAILIMAGEPROVIDER_CTHUMBNAILIMAGEPROVIDER 0x860036
#define CTHUMBNAILIMAGEPROVIDER_GETTHUMBNAILL 0x860037
#define DUP1_CTHUMBNAILIMAGEPROVIDER_GETTHUMBNAILL 0x860038
#define DUP2_CTHUMBNAILIMAGEPROVIDER_GETTHUMBNAILL 0x860039
#define DUP3_CTHUMBNAILIMAGEPROVIDER_GETTHUMBNAILL 0x86003a
#define DUP4_CTHUMBNAILIMAGEPROVIDER_GETTHUMBNAILL 0x86003b
#define DUP5_CTHUMBNAILIMAGEPROVIDER_GETTHUMBNAILL 0x86003c


#endif

// End of file

