/*
* Copyright (c) 2007 - 2008 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  String Dictionary for OMA 2.1 Drm
*
*/


// Autogenerated from DrmRel2_1StringDict00TagTable.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_DrmRel2_1StringDict00TagTable
#define STRINGTABLE_DrmRel2_1StringDict00TagTable

#include <stringpool.h>

struct TStringTable;

/** A String table */
class DrmRel2_1StringDict00TagTable 
	{
public:
	enum TStrings
		{
		// Element names
		// CodePage 00
		/** roap:roapTrigger */
		ERoapTrigger,
		/** roap:roapTrigger */
		ERoapTriggerWithContent,
		/** roap:roapTrigger */
		ERoapTriggerWithAttributes,
		/** roap:roapTrigger */
		ERoapTriggerWithContentAndAttributes,
		/** registrationRequest */
		ERegistrationRequest,
		/** registrationRequest */
		ERegistrationRequestWithContent,
		/** registrationRequest */
		ERegistrationRequestWithAttributes,
		/** registrationRequest */
		ERegistrationRequestWithContentAndAttributes,
		/** roAcquisition */
		EROAcquisition,
		/** roAcquisition */
		EROAcquisitionWithContent,
		/** roAcquisition */
		EROAcquisitionWithAttributes,
		/** roAcquisition */
		EROAcquisitionWithContentAndAttributes,
		/** joinDomain */
		EJoinDomain,
		/** joinDomain */
		EJoinDomainWithContent,
		/** joinDomain */
		EJoinDomainWithAttributes,
		/** joinDomain */
		EJoinDomainWithContentAndAttributes,
		/** leaveDomain */
		ELeaveDomain,
		/** leaveDomain */
		ELeaveDomainWithContent,
		/** leaveDomain */
		ELeaveDomainWithAttributes,
		/** leaveDomain */
		ELeaveDomainWithContentAndAttributes,
		/** signature */
		ESignature,
		/** signature */
		ESignatureWithContent,
		/** signature */
		ESignatureWithAttributes,
		/** signature */
		ESignatureWithContentAndAttributes,
		/** encKey */
		EEncKey,
		/** encKey */
		EEncKeyWithContent,
		/** encKey */
		EEncKeyWithAttributes,
		/** encKey */
		EEncKeyWithContentAndAttributes,
		/** riID */
		ERiId,
		/** riID */
		ERiIdWithContent,
		/** riID */
		ERiIdWithAttributes,
		/** riID */
		ERiIdWithContentAndAttributes,
		/** riAlias */
		ERiAlias,
		/** riAlias */
		ERiAliasWithContent,
		/** riAlias */
		ERiAliasWithAttributes,
		/** riAlias */
		ERiAliasWithContentAndAttributes,
		/** nonce */
		ENonce,
		/** nonce */
		ENonceWithContent,
		/** nonce */
		ENonceWithAttributes,
		/** nonce */
		ENonceWithContentAndAttributes,
		/** roapURL */
		ERoapUrl,
		/** roapURL */
		ERoapUrlWithContent,
		/** roapURL */
		ERoapUrlWithAttributes,
		/** roapURL */
		ERoapUrlWithContentAndAttributes,
		/** domainID */
		EDomainId,
		/** domainID */
		EDomainIdWithContent,
		/** domainID */
		EDomainIdWithAttributes,
		/** domainID */
		EDomainIdWithContentAndAttributes,
		/** domainAlias */
		EDomainAlias,
		/** domainAlias */
		EDomainAliasWithContent,
		/** domainAlias */
		EDomainAliasWithAttributes,
		/** domainAlias */
		EDomainAliasWithContentAndAttributes,
		/** roap:domainID */
		ERoapDomainId,
		/** roap:domainID */
		ERoapDomainIdWithContent,
		/** roap:domainID */
		ERoapDomainIdWithAttributes,
		/** roap:domainID */
		ERoapDomainIdWithContentAndAttributes,
		/** roID */
		ERoId,
		/** roID */
		ERoIdWithContent,
		/** roID */
		ERoIdWithAttributes,
		/** roID */
		ERoIdWithContentAndAttributes,
		/** roAlias */
		ERoAlias,
		/** roAlias */
		ERoAliasWithContent,
		/** roAlias */
		ERoAliasWithAttributes,
		/** roAlias */
		ERoAliasWithContentAndAttributes,
		/** contentID */
		EContentId,
		/** contentID */
		EContentIdWithContent,
		/** contentID */
		EContentIdWithAttributes,
		/** contentID */
		EContentIdWithContentAndAttributes,
		/** roap:X509SPKIHash */
		ERoapX509SPKIHash,
		/** roap:X509SPKIHash */
		ERoapX509SPKIHashWithContent,
		/** roap:X509SPKIHash */
		ERoapX509SPKIHashWithAttributes,
		/** roap:X509SPKIHash */
		ERoapX509SPKIHashWithContentAndAttributes,
		/** keyIdentifier */
		EKeyIdentifier,
		/** keyIdentifier */
		EKeyIdentifierWithContent,
		/** keyIdentifier */
		EKeyIdentifierWithAttributes,
		/** keyIdentifier */
		EKeyIdentifierWithContentAndAttributes,
		/** hash */
		EHash,
		/** hash */
		EHashWithContent,
		/** hash */
		EHashWithAttributes,
		/** hash */
		EHashWithContentAndAttributes,
		/** ds:SignedInfo */
		EDsSignedInfo,
		/** ds:SignedInfo */
		EDsSignedInfoWithContent,
		/** ds:SignedInfo */
		EDsSignedInfoWithAttributes,
		/** ds:SignedInfo */
		EDsSignedInfoWithContentAndAttributes,
		/** ds:SignatureValue */
		EDsSignatureValue,
		/** ds:SignatureValue */
		EDsSignatureValueWithContent,
		/** ds:SignatureValue */
		EDsSignatureValueWithAttributes,
		/** ds:SignatureValue */
		EDsSignatureValueWithContentAndAttributes,
		/** ds:KeyInfo */
		EDsKeyInfo,
		/** ds:KeyInfo */
		EDsKeyInfoWithContent,
		/** ds:KeyInfo */
		EDsKeyInfoWithAttributes,
		/** ds:KeyInfo */
		EDsKeyInfoWithContentAndAttributes,
		/** ds:CanonicalizationMethod */
		EDsCanonicalisationMethod,
		/** ds:CanonicalizationMethod */
		EDsCanonicalisationMethodWithContent,
		/** ds:CanonicalizationMethod */
		EDsCanonicalisationMethodWithAttributes,
		/** ds:CanonicalizationMethod */
		EDsCanonicalisationMethodWithContentAndAttributes,
		/** ds:SignatureMethod */
		EDsSignatureMethod,
		/** ds:SignatureMethod */
		EDsSignatureMethodWithContent,
		/** ds:SignatureMethod */
		EDsSignatureMethodWithAttributes,
		/** ds:SignatureMethod */
		EDsSignatureMethodWithContentAndAttributes,
		/** ds:Reference */
		EDsReference,
		/** ds:Reference */
		EDsReferenceWithContent,
		/** ds:Reference */
		EDsReferenceWithAttributes,
		/** ds:Reference */
		EDsReferenceWithContentAndAttributes,
		/** ds:RetrievalMethod */
		EDsRetrievalMethod,
		/** ds:RetrievalMethod */
		EDsRetrievalMethodWithContent,
		/** ds:RetrievalMethod */
		EDsRetrievalMethodWithAttributes,
		/** ds:RetrievalMethod */
		EDsRetrievalMethodWithContentAndAttributes,
		/** ds:Transforms */
		EDsTransforms,
		/** ds:Transforms */
		EDsTransformsWithContent,
		/** ds:Transforms */
		EDsTransformsWithAttributes,
		/** ds:Transforms */
		EDsTransformsWithContentAndAttributes,
		/** ds:DigestMethod */
		EDsDigestMethod,
		/** ds:DigestMethod */
		EDsDigestMethodWithContent,
		/** ds:DigestMethod */
		EDsDigestMethodWithAttributes,
		/** ds:DigestMethod */
		EDsDigestMethodWithContentAndAttributes,
		/** ds:DigestValue */
		EDsDigestValue,
		/** ds:DigestValue */
		EDsDigestValueWithContent,
		/** ds:DigestValue */
		EDsDigestValueWithAttributes,
		/** ds:DigestValue */
		EDsDigestValueWithContentAndAttributes,
		/** ds:Transform */
		EDsTransform,
		/** ds:Transform */
		EDsTransformWithContent,
		/** ds:Transform */
		EDsTransformWithAttributes,
		/** ds:Transform */
		EDsTransformWithContentAndAttributes,
		/** xenc:EncryptionMethod */
		EXencEncryptionMethod,
		/** xenc:EncryptionMethod */
		EXencEncryptionMethodWithContent,
		/** xenc:EncryptionMethod */
		EXencEncryptionMethodWithAttributes,
		/** xenc:EncryptionMethod */
		EXencEncryptionMethodWithContentAndAttributes,
		/** xenc:CipherData */
		EXencCipherData,
		/** xenc:CipherData */
		EXencCipherDataWithContent,
		/** xenc:CipherData */
		EXencCipherDataWithAttributes,
		/** xenc:CipherData */
		EXencCipherDataWithContentAndAttributes,
		/** xenc:CipherValue */
		EXencCipherValue,
		/** xenc:CipherValue */
		EXencCipherValueWithContent,
		/** xenc:CipherValue */
		EXencCipherValueWithAttributes,
		/** xenc:CipherValue */
		EXencCipherValueWithContentAndAttributes,
		/** extendedTrigger */
		EExtentedTrigger,
		/** extendedTrigger */
		EExtentedTriggerWithContent,
		/** extendedTrigger */
		EExtentedTriggerWithAttributes,
		/** extendedTrigger */
		EExtentedTriggerWithContentAndAttributes,
		/** trgLeaveDomain */
		ETrgLeaveDomain,
		/** trgLeaveDomain */
		ETrgLeaveDomainWithContent,
		/** trgLeaveDomain */
		ETrgLeaveDomainWithAttributes,
		/** trgLeaveDomain */
		ETrgLeaveDomainWithContentAndAttributes,
		/** deviceID */
		EDeviceId,
		/** deviceID */
		EDeviceIdWithContent,
		/** deviceID */
		EDeviceIdWithAttributes,
		/** deviceID */
		EDeviceIdWithContentAndAttributes,
		// For XML
		/** -//OMA/DRM 2.1//EN */
		EUri,
		// For WBXML
		/** 13~0 */
		EPublicId,
		/** -//OMA/DRM 2.1//EN~0 */
		EFormalPublicId
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_DrmRel2_1StringDict00TagTable

