/*
* Copyright (c) 2007 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  String Dictionary for OMA 2.1 Drm
*
*/


// Autogenerated from epoc32\build\generated\Xml\DrmRel2_1StringDict00AttributeTable.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_DrmRel2_1StringDict00AttributeTable
#define STRINGTABLE_DrmRel2_1StringDict00AttributeTable

#include "stringpool.h"

struct TStringTable;

/** A String table */
class DrmRel2_1StringDict00AttributeTable 
	{
public:
	enum TStrings
		{
		// Element names
		// CodePage 00
		/** xsi:type */
		EXsiType,
		/** xmlns:roap */
		EXmlnsRoap,
		/** xmlns:xsi */
		EXmlnsXsi,
		/** xmlns:xenc */
		EXmlnsXenc,
		/** xmlns:ds */
		EXmlnsDs,
		/** xmlns:o-ex */
		EXmlnsOex,
		/** xmlns:o-dd */
		EXmlnsOdd,
		/** xmlns:oma-dd */
		EXmlnsOmadd,
		/** version */
		EVersion,
		/** proxy */
		EProxy,
		/** id */
		EId,
		/** Id */
		EId2,
		/** algorithm */
		ELCAlgorithm,
		/** Algorithm */
		EHCAlgorithm,
		/** URI */
		EUri,
		/** type */
		EType
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_DrmRel2_1StringDict00AttributeTable

