/*
* Copyright (c) 2007 - 2008 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  String Dictionary for OMA 2.1 Drm
*
*/


// Autogenerated from DrmRel2_1StringDict00AttributeValueTable.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_DrmRel2_1StringDict00AttributeValueTable
#define STRINGTABLE_DrmRel2_1StringDict00AttributeValueTable

#include <stringpool.h>

struct TStringTable;

/** A String table */
class DrmRel2_1StringDict00AttributeValueTable 
	{
public:
	enum TStrings
		{
		// Element names
		// CodePage 00
		/**  */
		EXsiTypeValue,
		/**  */
		EXmlnsRoapValue,
		/**  */
		EXmlnsXsiValue,
		/**  */
		EXmlnsXencValue,
		/**  */
		EXmlnsDsValue,
		/**  */
		EXmlnsOexValue,
		/**  */
		EXmlnsOddValue,
		/**  */
		EXmlnsOmaddValue,
		/**  */
		EVersionValue,
		/**  */
		EProxyValue,
		/**  */
		EIdValue,
		/**  */
		EId2Value,
		/**  */
		ELCAlgorithmValue,
		/**  */
		EHCAlgorithmValue,
		/**  */
		EUriValue,
		/**  */
		ETypeValue,
		/** urn:oma:bac:dldrm:roap-1.0 */
		EUrn,
		/** http://odrl.net/1.1/ODRL-EX */
		EOdrlEx,
		/** http://odrl.net/1.1/ODRL-DD */
		EOdrlDd,
		/** http://www.openmobilealliance.com/oma-dd */
		EOmaDd,
		/** http://www.w3.org/2000/09/xmldsig# */
		EXmldSig,
		/** http://www.w3.org/2001/04/xmlenc# */
		EXmlEnc,
		/** http://www.w3.org/2001/XMLSchema-instance */
		EXmlSchema,
		/** roap:X509SPKIHash */
		ERoapX509SPKIHashValue,
		/** http://www.w3.org/2000/09/xmldsig#sha1 */
		EXmldSigSha1,
		/** http://www.w3.org/2001/10/xml-exc-c14n# */
		EXmlExcC14,
		/** http://www.w3.org/2000/09/xmldsig#hmac-sha1 */
		EXmldSigHmacSha1,
		/** 1.1 */
		EVersion1,
		/** 2.0 */
		EVersion2,
		/** 2.1 */
		EVersion21,
		/** identificationRequest */
		EIdentificationRequest,
		/** roUploadRequest */
		ERoUploadRequest,
		/** meteringReport */
		EMeteringReport,
		/** leaveDomain */
		ELeaveDomainValue
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_DrmRel2_1StringDict00AttributeValueTable

