// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestSuiteName DstIntServer
//! @SYMScriptTestEnvironment

LOAD_SUITE DstIntServer

START_TESTCASE PIM-TestDSTChanges-0001
//! @SYMTestCaseID PIM-TestDSTChanges-0001
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini LondonDSTStart
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini LondonDSTEnd
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini SydneyDSTStart
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini SydneyDSTEnd
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini ChicagoDSTStart
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini ChicagoDSTEnd
END_TESTCASE PIM-TestDSTChanges-0001

START_TESTCASE PIM-TestNoDSTChanges-0001
//! @SYMTestCaseID PIM-TestNoDSTChanges-0001
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini TokyoNoDST
END_TESTCASE PIM-TestNoDSTChanges-0001

START_TESTCASE PIM-TestAutoUpdatesOff-0001
//! @SYMTestCaseID PIM-TestAutoUpdatesOff-0001
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini LondonAutoUpdatesOff
RUN_TEST_STEP 100 DstIntServer NextDSTChange \dstscripts\NextDSTChange.ini TokyoAutoUpdatesOff
END_TESTCASE PIM-TestAutoUpdatesOff-0001

START_TESTCASE PIM-TestPublishOnTzChange-0001
//! @SYMTestCaseID PIM-TestPublishOnTzChange-0001
RUN_TEST_STEP 100 DstIntServer SetSysTime \dstscripts\NextDSTChange.ini LondonDSTStart
RUN_TEST_STEP 100 DstIntServer SetTz \dstscripts\NextDSTChange.ini TokyoAutoUpdatesOff
CONCURRENT
RUN_TEST_STEP 100 DstIntServer SubscribeNextDSTChange \dstscripts\NextDSTChange.ini LondonDSTStart 
RUN_TEST_STEP 100 DstIntServer SetTz \dstscripts\NextDSTChange.ini LondonDSTStart DELAY 10000
CONSECUTIVE
END_TESTCASE PIM-TestPublishOnTzChange-0001

START_TESTCASE PIM-TestPublishOnSystemTimeChange-0001
//! @SYMTestCaseID PIM-TestPublishOnSystemTimeChange-0001
RUN_TEST_STEP 100 DstIntServer SetSysTime \dstscripts\NextDSTChange.ini LondonDSTStart
RUN_TEST_STEP 100 DstIntServer SetTz \dstscripts\NextDSTChange.ini LondonDSTStart
CONCURRENT
RUN_TEST_STEP 100 DstIntServer SubscribeNextDSTChange \dstscripts\NextDSTChange.ini LondonDSTEnd
RUN_TEST_STEP 100 DstIntServer SetSysTime \dstscripts\NextDSTChange.ini LondonDSTEnd DELAY 10000
CONSECUTIVE
END_TESTCASE PIM-TestPublishOnSystemTimeChange-0001

START_TESTCASE PIM-TestPublishOnDSTRollover-0001
//! @SYMTestCaseID PIM-TestPublishOnDSTRollover-0001
RUN_TEST_STEP 100 DstIntServer SetSysTime \dstscripts\NextDSTChange.ini LondonDSTRollover
RUN_TEST_STEP 100 DstIntServer SetTz \dstscripts\NextDSTChange.ini LondonDSTRollover
RUN_TEST_STEP 100 DstIntServer SubscribeNextDSTChange \dstscripts\NextDSTChange.ini LondonDSTRollover DELAY 10000
END_TESTCASE PIM-TestPublishOnDSTRollover-0001

START_TESTCASE PIM-TestDoNotPublishWhenSystemTimeChangeDoesntAffectValues-0001
//! @SYMTestCaseID PIM-TestDoNotPublishWhenSystemTimeChangeDoesntAffectValues-0001
RUN_TEST_STEP 100 DstIntServer SetSysTime \dstscripts\NextDSTChange.ini LondonDSTStart
RUN_TEST_STEP 100 DstIntServer SetTz \dstscripts\NextDSTChange.ini LondonDSTStart
CONCURRENT
RUN_TEST_STEP !Result=-39 2 DstIntServer SubscribeNextDSTChange \dstscripts\NextDSTChange.ini LondonDSTStart
RUN_TEST_STEP 100 DstIntServer SetSysTime \dstscripts\NextDSTChange.ini LondonDSTStart DELAY 10000
CONSECUTIVE
END_TESTCASE PIM-TestDoNotPublishWhenSystemTimeChangeDoesntAffectValues-0001

START_TESTCASE PIM-TestDoNotPublishWhenTimeZoneChangeDoesntAffectValues-0001
//! @SYMTestCaseID PIM-TestDoNotPublishWhenTimeZoneChangeDoesntAffectValues-0001
RUN_TEST_STEP 100 DstIntServer SetSysTime \dstscripts\NextDSTChange.ini LondonDSTStart
RUN_TEST_STEP 100 DstIntServer SetTz \dstscripts\NextDSTChange.ini LondonDSTStart
CONCURRENT
RUN_TEST_STEP !Result=-39 2 DstIntServer SubscribeNextDSTChange \dstscripts\NextDSTChange.ini LondonDSTStart
RUN_TEST_STEP 100 DstIntServer SetTz \dstscripts\NextDSTChange.ini LondonDSTStart DELAY 10000
CONSECUTIVE
END_TESTCASE PIM-TestDoNotPublishWhenTimeZoneChangeDoesntAffectValues-0001



