//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// Load the DST test server
LOAD_SUITE DstIntServer -SharedData

START_TESTCASE   PIM-PERFORMANCETEST-0001
//! @SYMTestCaseID   PIM-PERFORMANCETEST-0001
RUN_TEST_STEP 100 DstIntServer Performance	\dstscripts\performance.ini PerformanceTest0001
END_TESTCASE   PIM-PERFORMANCETEST-0001


