// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestSuiteName DstIntServer
//! @SYMScriptTestEnvironment

LOAD_SUITE DstIntServer

START_TESTCASE   PIM-UNKNOWNZONETIME-0001
//! @SYMTestCaseID   PIM-UNKNOWNZONETIME-0001
RUN_TEST_STEP 100 DstIntServer UnknownZoneTime
END_TESTCASE   PIM-UNKNOWNZONETIME-0001