//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// Load the DST test server
LOAD_SUITE DstIntServer -SharedData


START_TESTCASE   PIM-UTCALARMTEST-0001
//! @SYMTestCaseID   PIM-UTCALARMTEST-0001
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest01
END_TESTCASE   PIM-UTCALARMTEST-0001
START_TESTCASE   PIM-UTCALARMTEST-0002
//! @SYMTestCaseID   PIM-UTCALARMTEST-0002
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest02
END_TESTCASE   PIM-UTCALARMTEST-0002
START_TESTCASE   PIM-UTCALARMTEST-0003
//! @SYMTestCaseID   PIM-UTCALARMTEST-0003
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest03
END_TESTCASE   PIM-UTCALARMTEST-0003
START_TESTCASE   PIM-UTCALARMTEST-0004
//! @SYMTestCaseID   PIM-UTCALARMTEST-0004
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest04
END_TESTCASE   PIM-UTCALARMTEST-0004
START_TESTCASE   PIM-UTCALARMTEST-0005
//! @SYMTestCaseID   PIM-UTCALARMTEST-0005
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest05
END_TESTCASE   PIM-UTCALARMTEST-0005
START_TESTCASE   PIM-UTCALARMTEST-0006
//! @SYMTestCaseID   PIM-UTCALARMTEST-0006
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest06
END_TESTCASE   PIM-UTCALARMTEST-0006
START_TESTCASE   PIM-UTCALARMTEST-0007
//! @SYMTestCaseID   PIM-UTCALARMTEST-0007
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest07
END_TESTCASE   PIM-UTCALARMTEST-0007
START_TESTCASE   PIM-UTCALARMTEST-0008
//! @SYMTestCaseID   PIM-UTCALARMTEST-0008
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest08
END_TESTCASE   PIM-UTCALARMTEST-0008
START_TESTCASE   PIM-UTCALARMTEST-0009
//! @SYMTestCaseID   PIM-UTCALARMTEST-0009
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest09
END_TESTCASE   PIM-UTCALARMTEST-0009
START_TESTCASE   PIM-UTCALARMTEST-0010
//! @SYMTestCaseID   PIM-UTCALARMTEST-0010
RUN_TEST_STEP 100 DstIntServer UTCAlarm \dstscripts\utcalarm.ini UTCAlarmTest10
END_TESTCASE   PIM-UTCALARMTEST-0010
