// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TMFORMATOBSERVERTRACES_H__
#define __TMFORMATOBSERVERTRACES_H__

#define KOstTraceComponentID 0x2001fd51

#define CTMFORMATOBSERVER_CTMFORMATOBSERVER 0x8600e3
#define CTMFORMATOBSERVER_CONSTRUCTL 0x8600e4
#define CTMFORMATOBSERVER_POLLSTATUS 0x8600e5
#define CTMFORMATOBSERVER_HANDLEBACKUPOPERATIONEVENTL 0x8600e6


#endif

// End of file

