// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TMSHUTDOWNOBSERVERTRACES_H__
#define __TMSHUTDOWNOBSERVERTRACES_H__

#define KOstTraceComponentID 0x2001fd51

#define CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8600e7
#define DUP1_CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8600e8
#define DUP2_CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8600e9
#define DUP3_CTMSHUTDOWNOBSERVER_CONSTRUCTL 0x8600ea
#define CTMSHUTDOWNOBSERVER_CTMSHUTDOWNOBSERVER 0x8600eb
#define CTMSHUTDOWNOBSERVER_RUNL 0x8600ec
#define DUP1_CTMSHUTDOWNOBSERVER_RUNL 0x8600ed
#define CTMSHUTDOWNOBSERVER_DOCANCEL 0x8600ee


#endif

// End of file

