// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TMSRPROPTERTYOBSERVERTRACES_H__
#define __TMSRPROPTERTYOBSERVERTRACES_H__

#define KOstTraceComponentID 0x2001fd51

#define CTMRPROPERTYOBSERVER_CONSTRUCTL 0x8600ef
#define CTMRPROPERTYOBSERVER_CTMRPROPERTYOBSERVER 0x8600f0
#define CTMRPROPERTYOBSERVER_RUNL 0x8600f1
#define CTMRPROPERTYOBSERVER_DOCANCEL 0x8600f2


#endif

// End of file

