// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PREFIX RUN_UTILS
// Overwrite the RSC file
MakeReadWrite c:\Private\101F5027\AlarmServer.rsc
CopyFile \test\pim\alarmserver\config\defaultinterval.rsc c:\Private\101F5027\AlarmServer.rsc
REMOVE_PREFIX
DELAY 1000
RUN_SCRIPT \test\pim\alarmserver\scripts\defaultinterval.script



PREFIX RUN_UTILS
// Overwrite the RSC file
MakeReadWrite c:\Private\101F5027\AlarmServer.rsc
CopyFile \test\pim\alarmserver\config\repeatlast.rsc c:\Private\101F5027\AlarmServer.rsc
REMOVE_PREFIX
DELAY 1000
RUN_SCRIPT \test\pim\alarmserver\scripts\repeatlast.script



PREFIX RUN_UTILS
// Overwrite the RSC file
MakeReadWrite c:\Private\101F5027\AlarmServer.rsc
CopyFile \test\pim\alarmserver\config\stopinterval.rsc c:\Private\101F5027\AlarmServer.rsc
REMOVE_PREFIX
DELAY 1000
RUN_SCRIPT \test\pim\alarmserver\scripts\stopinterval.script



PREFIX RUN_UTILS
// Overwrite the RSC file
MakeReadWrite c:\Private\101F5027\AlarmServer.rsc
CopyFile \test\pim\alarmserver\config\disableinterval.rsc c:\Private\101F5027\AlarmServer.rsc
REMOVE_PREFIX
DELAY 1000
RUN_SCRIPT \test\pim\alarmserver\scripts\disableinterval.script

PREFIX RUN_UTILS
MakeReadWrite c:\Private\101F5027\AlarmServer.rsc
DeleteFile c:\Private\101F5027\AlarmServer.rsc
REMOVE_PREFIX
