// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE T_PREQ1118_TestSuite

START_TESTCASE PIM_APPSRV-ALARMSVR-CIT-1118-0014
//! @file
//! @SYMTestCaseID PIM_APPSRV-ALARMSVR-CIT-1118-0014
//! @SYMTestType CIT
//! @SYMTestPriority High
//! @SYMPREQ 1118
//! @SYMFssID AlarmServer 034
//! @SYMTestStatus Implemented
//! @SYMTestCaseDesc Alarm Notification Using Repeating Last Play Interval
//! @SYMTestActions  Resource file has last play interval set. Add and alarm,
//!                  wait for it to expire, check play interval timing
//! @SYMTestExpectedResults The las play interval is continually repeated.

PREFIX RUN_UTILS
// Remove the INI file
MakeReadWrite c:\Private\101F5027\AlarmServer.ini
DeleteFile c:\Private\101F5027\AlarmServer.ini
REMOVE_PREFIX

RUN_TEST_STEP 500 T_PREQ1118_TestSuite TestRepeatLastIntervalStep \test\pim\alarmserver\data\citalarmplaytestdata.ini RepeatPlayInterval
END_TESTCASE PIM_APPSRV-ALARMSVR-CIT-1118-0014
