// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __THUMBNAILAUDIOPROVIDERTRACES_H__
#define __THUMBNAILAUDIOPROVIDERTRACES_H__

#define KOstTraceComponentID 0x20022d5d

#define CTHUMBNAILAUDIOPROVIDER_CTHUMBNAILAUDIOPROVIDER 0x860001
#define CTHUMBNAILAUDIOPROVIDER_GETTHUMBNAILL 0x860002
#define DUP1_CTHUMBNAILAUDIOPROVIDER_GETTHUMBNAILL 0x860003
#define DUP2_CTHUMBNAILAUDIOPROVIDER_GETTHUMBNAILL 0x860004
#define DUP1_CTHUMBNAILAUDIOPROVIDER_CTHUMBNAILAUDIOPROVIDER 0x86000f


#endif

// End of file

