// Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// apfrec.h
//

#ifndef __APFREC_H__
#define __APFREC_H__

#include <apadef.h>
#include <apaflrec.h>
#include <babackup.h>

class TApaAppEntry;
class TEntry;
class RFs;
class TDriveUnit;


#endif	// __APFREC_H__
