/*
* ==============================================================================
*  Name        : ProfilesWrapperExports.inc
*  Part of     : Profiles Engine
*  Interface   : ?Interface_category, ?Interface_name
*  Description : ?Description
*  Version     : ?Version
*
*  Copyright (c) 2002 Nokia Corporation.
*  This material, including documentation and any related
*  computer programs, is protected by copyright controlled by
*  Nokia Corporation. All rights are reserved. Copying,
*  including reproducing, storing, adapting or translating, any
*  or all of this material requires the prior written consent of
*  Nokia Corporation. This material also contains confidential
*  information which may not be disclosed to others without the
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/
// To get the APP_LAYER_SYSTEMINCLUDE-definition
#include <platform_paths.hrh>


#ifndef PROFILESWRAPPEREXPORTS_INC
#define PROFILESWRAPPEREXPORTS_INC

    ../WrapperInc/MProEngActiveProfileObserver.h    APP_LAYER_PUBLIC_EXPORT_PATH(MProEngActiveProfileObserver.h)
    ../WrapperInc/MProEngAlertToneSeeker.h          APP_LAYER_PUBLIC_EXPORT_PATH(MProEngAlertToneSeeker.h)
    ../WrapperInc/MProEngAlertToneSeekerObserver.h  APP_LAYER_PUBLIC_EXPORT_PATH(MProEngAlertToneSeekerObserver.h)
    ../WrapperInc/MProEngEngine.h          APP_LAYER_PUBLIC_EXPORT_PATH(MProEngEngine.h)
    ../WrapperInc/MProEngNotifyHandler.h   APP_LAYER_PUBLIC_EXPORT_PATH(MProEngNotifyHandler.h)
    ../WrapperInc/MProEngProfile.h         APP_LAYER_PUBLIC_EXPORT_PATH(MProEngProfile.h)
    ../WrapperInc/MProEngProfileActivationObserver.h APP_LAYER_PUBLIC_EXPORT_PATH(MProEngProfileActivationObserver.h)
    ../WrapperInc/MProEngProfileName.h          APP_LAYER_PUBLIC_EXPORT_PATH(MProEngProfileName.h)
    ../WrapperInc/MProEngProfileNameArray.h          APP_LAYER_PUBLIC_EXPORT_PATH(MProEngProfileNameArray.h)
    ../WrapperInc/MProEngProfileNameArrayObserver.h  APP_LAYER_PUBLIC_EXPORT_PATH(MProEngProfileNameArrayObserver.h)
    ../WrapperInc/MProEngProfileObserver.h          APP_LAYER_PUBLIC_EXPORT_PATH(MProEngProfileObserver.h)
    ../WrapperInc/MProEngTones.h          APP_LAYER_PUBLIC_EXPORT_PATH(MProEngTones.h)
    ../WrapperInc/MProEngToneSettings.h   APP_LAYER_PUBLIC_EXPORT_PATH(MProEngToneSettings.h)
    ../WrapperInc/ProEngFactory.h         APP_LAYER_PUBLIC_EXPORT_PATH(ProEngFactory.h)

#endif      // PROFILESWRAPPEREXPORTS_INC

// End of File

