// Created by TraceCompiler1.1.6
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TACTILEAUDIOPLAYERTRACES_H__
#define __TACTILEAUDIOPLAYERTRACES_H__

#define KOstTraceComponentID 0x20021339

#define TACTILE_PLAY_AUDIO_FEEDBACK_1 0x400001
#define TACTILE_PLAY_AUDIO_FEEDBACK_0 0x400002


#endif

// End of file

