// Created by TraceCompiler1.1.6
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TACTILEHAPTICSPLAYERTRACES_H__
#define __TACTILEHAPTICSPLAYERTRACES_H__

#define KOstTraceComponentID 0x2001cb98

#define TACTILE_PLAY_HAPTICS_FEEDBACK_1 0x400001
#define TACTILE_PLAY_HAPTICS_FEEDBACK_0 0x400002


#endif

// End of file

