# DrmRel2_1StringDict00AttributeTable.st
# Copyright © 2008 Nokia.  All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
stringtable DrmRel2_1StringDict00AttributeTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EXsiType xsi:type
EXmlnsRoap xmlns:roap
EXmlnsXsi xmlns:xsi
EXmlnsXenc xmlns:xenc
EXmlnsDs xmlns:ds
EXmlnsOex xmlns:o-ex
EXmlnsOdd xmlns:o-dd
EXmlnsOmadd xmlns:oma-dd
EVersion version
EProxy proxy
EId id
EId2 Id
ELCAlgorithm algorithm
EHCAlgorithm Algorithm
EUri URI
EType type