/*
* Copyright (c) 2008 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  String Dictionary for OMA 2.1 Drm
*
*/


// Autogenerated from DrmRel2_1StringDict00AttributeValueTable.st by the stringtable tool - Do not edit
#include <e32std.h>
#include <stringpool.h>
#include <stringtablesupport.h>
#include "drmrel2_1stringdict00attributevaluetable.h"
#ifdef _DEBUG
#undef _DEBUG
#endif

_STLIT8(K1, "");
_STLIT8(K2, "");
_STLIT8(K3, "");
_STLIT8(K4, "");
_STLIT8(K5, "");
_STLIT8(K6, "");
_STLIT8(K7, "");
_STLIT8(K8, "");
_STLIT8(K9, "");
_STLIT8(K10, "");
_STLIT8(K11, "");
_STLIT8(K12, "");
_STLIT8(K13, "");
_STLIT8(K14, "");
_STLIT8(K15, "");
_STLIT8(K16, "");
_STLIT8(K17, "urn:oma:bac:dldrm:roap-1.0");
_STLIT8(K18, "http://odrl.net/1.1/ODRL-EX");
_STLIT8(K19, "http://odrl.net/1.1/ODRL-DD");
_STLIT8(K20, "http://www.openmobilealliance.com/oma-dd");
_STLIT8(K21, "http://www.w3.org/2000/09/xmldsig#");
_STLIT8(K22, "http://www.w3.org/2001/04/xmlenc#");
_STLIT8(K23, "http://www.w3.org/2001/XMLSchema-instance");
_STLIT8(K24, "roap:X509SPKIHash");
_STLIT8(K25, "http://www.w3.org/2000/09/xmldsig#sha1");
_STLIT8(K26, "http://www.w3.org/2001/10/xml-exc-c14n#");
_STLIT8(K27, "http://www.w3.org/2000/09/xmldsig#hmac-sha1");
_STLIT8(K28, "1.1");
_STLIT8(K29, "2.0");
_STLIT8(K30, "2.1");
_STLIT8(K31, "identificationRequest");
_STLIT8(K32, "roUploadRequest");
_STLIT8(K33, "meteringReport");
_STLIT8(K34, "leaveDomain");

// Intermediate
const void * const KStringPointers[] =
	{
	(const void*)&K1,
	(const void*)&K2,
	(const void*)&K3,
	(const void*)&K4,
	(const void*)&K5,
	(const void*)&K6,
	(const void*)&K7,
	(const void*)&K8,
	(const void*)&K9,
	(const void*)&K10,
	(const void*)&K11,
	(const void*)&K12,
	(const void*)&K13,
	(const void*)&K14,
	(const void*)&K15,
	(const void*)&K16,
	(const void*)&K17,
	(const void*)&K18,
	(const void*)&K19,
	(const void*)&K20,
	(const void*)&K21,
	(const void*)&K22,
	(const void*)&K23,
	(const void*)&K24,
	(const void*)&K25,
	(const void*)&K26,
	(const void*)&K27,
	(const void*)&K28,
	(const void*)&K29,
	(const void*)&K30,
	(const void*)&K31,
	(const void*)&K32,
	(const void*)&K33,
	(const void*)&K34
	};

const TStringTable DrmRel2_1StringDict00AttributeValueTable::Table = {34, KStringPointers, ETrue};
