/*
* Copyright (c) 2008 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  String Dictionary for OMA 2.1 Drm
*
*/

// Autogenerated from epoc32\build\generated\Xml\DrmRel2_1StringDict00AttributeTable.st by the stringtable tool - Do not edit
#include <e32std.h>
#include "stringpool.h"
#include "stringtablesupport.h"
#include "drmrel2_1stringdict00attributetable.h"
#ifdef _DEBUG
#undef _DEBUG
#endif

_STLIT8(K1, "xsi:type");
_STLIT8(K2, "xmlns:roap");
_STLIT8(K3, "xmlns:xsi");
_STLIT8(K4, "xmlns:xenc");
_STLIT8(K5, "xmlns:ds");
_STLIT8(K6, "xmlns:o-ex");
_STLIT8(K7, "xmlns:o-dd");
_STLIT8(K8, "xmlns:oma-dd");
_STLIT8(K9, "version");
_STLIT8(K10, "proxy");
_STLIT8(K11, "id");
_STLIT8(K12, "Id");
_STLIT8(K13, "algorithm");
_STLIT8(K14, "Algorithm");
_STLIT8(K15, "URI");
_STLIT8(K16, "type");

// Intermediate
const void * const KStringPointers[] =
	{
	(const void*)&K1,
	(const void*)&K2,
	(const void*)&K3,
	(const void*)&K4,
	(const void*)&K5,
	(const void*)&K6,
	(const void*)&K7,
	(const void*)&K8,
	(const void*)&K9,
	(const void*)&K10,
	(const void*)&K11,
	(const void*)&K12,
	(const void*)&K13,
	(const void*)&K14,
	(const void*)&K15,
	(const void*)&K16
	};

const TStringTable DrmRel2_1StringDict00AttributeTable::Table = {16, KStringPointers, ETrue};
