# DrmRel2_1StringDict00AttributeValueTable.st
# Copyright © 2008 Nokia.  All rights reserved..
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
stringtable DrmRel2_1StringDict00AttributeValueTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EXsiTypeValue  
EXmlnsRoapValue  
EXmlnsXsiValue  
EXmlnsXencValue  
EXmlnsDsValue  
EXmlnsOexValue  
EXmlnsOddValue  
EXmlnsOmaddValue  
EVersionValue  
EProxyValue  
EIdValue  
EId2Value  
ELCAlgorithmValue  
EHCAlgorithmValue  
EUriValue  
ETypeValue  
EUrn urn:oma:bac:dldrm:roap-1.0
EOdrlEx http://odrl.net/1.1/ODRL-EX
EOdrlDd http://odrl.net/1.1/ODRL-DD
EOmaDd http://www.openmobilealliance.com/oma-dd
EXmldSig http://www.w3.org/2000/09/xmldsig#
EXmlEnc http://www.w3.org/2001/04/xmlenc#
EXmlSchema http://www.w3.org/2001/XMLSchema-instance
ERoapX509SPKIHashValue roap:X509SPKIHash
EXmldSigSha1 http://www.w3.org/2000/09/xmldsig#sha1
EXmlExcC14 http://www.w3.org/2001/10/xml-exc-c14n#
EXmldSigHmacSha1 http://www.w3.org/2000/09/xmldsig#hmac-sha1
EVersion1 1.1
EVersion2 2.0
EVersion21 2.1
EIdentificationRequest identificationRequest
ERoUploadRequest roUploadRequest
EMeteringReport meteringReport
ELeaveDomainValue leaveDomain
