// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @test
//! @internalComponent - Internal Symbian test code 
//! @SYMTestCaseID 		API-APPFWK-CREATENEW-0001
//! @SYMTestStatus		3. Released

LOAD_SUITE tdscstore_server

RUN_SCRIPT z:\amastarttest\ini\tdscstore_dscdb_backup.script

START_TESTCASE API-APPFWK-CREATENEW-0001

PRINT Delete DBMS ddbb so we can create a custom one for test purposes
RUN_UTILS DeleteFile 	c:\private\100012a5\DBS_2000836D_DBS_DSC.db


PRINT Create a new DBMS ddbb for the tests
RUN_TEST_STEP 			100 tdscstore_server CreateDsc 		z:\amastarttest\ini\tdscstore_api.ini Dsc_DefaultUid
RUN_TEST_STEP 			100 tdscstore_server CreateDsc 		z:\amastarttest\ini\tdscstore_api.ini Dsc_1
RUN_TEST_STEP 			100 tdscstore_server CreateDscItem 	z:\amastarttest\ini\tdscstore_api.ini AMC_1_DSC1
RUN_TEST_STEP 			100 tdscstore_server CreateDscItem 	z:\amastarttest\ini\tdscstore_api.ini AMC_2_DSC1
RUN_TEST_STEP 			100 tdscstore_server CreateDscItem 	z:\amastarttest\ini\tdscstore_api.ini AMC_3_DSC1
RUN_TEST_STEP 			100 tdscstore_server CreateDscItem 	z:\amastarttest\ini\tdscstore_api.ini AMC_4_DSC1
RUN_TEST_STEP 			100 tdscstore_server CreateDscItem 	z:\amastarttest\ini\tdscstore_api.ini AMC_1_DefaultUid


PRINT Backup newly created test DBMS ddbb
RUN_UTILS CopyFile 	c:\private\100012a5\DBS_2000836D_DBS_DSC.db c:\private\100012a5\DBS_2000836D_DBS_DSC.db.testbackup

END_TESTCASE API-APPFWK-CREATENEW-0001