stringtable DrmRel1_0StringDict00TagTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
# //////////////////////////////////////////////////////////////////////
ERights rights
EContext context
EVersion version
EUid uid
EAgreement agreement
EAsset asset
EKeyInfo KeyInfo
EKeyValue KeyValue
EPermission permission
EPlay play
EDisplay display
EExecute execute
EPrint print
EConstraint constraint
ECount count
EDateTime datetime
EStart start
EEnd end
EInterval interval
EUri						-//OMA//DTD DRMREL 1.0//EN
EPublicId					E~0
EFormalPublicId				-//OMA//DTD DRMREL 1.0//EN~0
