/*
* Copyright (c) 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Implementation of a parser for protected OMA DRM rights
*
*/


// Autogenerated from \epoc32\build\generated\Xml\DrmRel1_0StringDict00TagTable.st by the stringtable tool - Do not edit
#include <e32std.h>
#include "stringpool.h"
#include "stringtablesupport.h"
#include "DrmRel1_0StringDict00TagTable.h"
#ifdef _DEBUG
#undef _DEBUG
#endif

_STLIT8(K1, "rights");
_STLIT8(K2, "context");
_STLIT8(K3, "version");
_STLIT8(K4, "uid");
_STLIT8(K5, "agreement");
_STLIT8(K6, "asset");
_STLIT8(K7, "KeyInfo");
_STLIT8(K8, "KeyValue");
_STLIT8(K9, "permission");
_STLIT8(K10, "play");
_STLIT8(K11, "display");
_STLIT8(K12, "execute");
_STLIT8(K13, "print");
_STLIT8(K14, "constraint");
_STLIT8(K15, "count");
_STLIT8(K16, "datetime");
_STLIT8(K17, "start");
_STLIT8(K18, "end");
_STLIT8(K19, "interval");
_STLIT8(K20, "-//OMA//DTD DRMREL 1.0//EN");
_STLIT8(K21, "14~0");
_STLIT8(K22, "-//OMA//DTD DRMREL 1.0//EN~0");

// Intermediate
const void * const KStringPointers[] =
    {
    (const void*)&K1,
    (const void*)&K2,
    (const void*)&K3,
    (const void*)&K4,
    (const void*)&K5,
    (const void*)&K6,
    (const void*)&K7,
    (const void*)&K8,
    (const void*)&K9,
    (const void*)&K10,
    (const void*)&K11,
    (const void*)&K12,
    (const void*)&K13,
    (const void*)&K14,
    (const void*)&K15,
    (const void*)&K16,
    (const void*)&K17,
    (const void*)&K18,
    (const void*)&K19,
    (const void*)&K20,
    (const void*)&K21,
    (const void*)&K22
    };

const TStringTable DrmRel1_0StringDict00TagTable::Table = {22, KStringPointers, ETrue};
