/*
* Copyright (c) 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Implementation of a parser for protected OMA DRM rights
*
*/


// Autogenerated from \epoc32\build\generated\Xml\DrmRel1_0StringDict00AttributeValueTable.st by the stringtable tool - Do not edit
#include <e32std.h>
#include "stringpool.h"
#include "stringtablesupport.h"
#include "DrmRel1_0StringDict00AttributeValueTable.h"
#ifdef _DEBUG
#undef _DEBUG
#endif

_STLIT8(K1, "");
_STLIT8(K2, "");
_STLIT8(K3, "");
_STLIT8(K4, "http://odrl.net/1.1/ODRL-EX");
_STLIT8(K5, "http://odrl.net/1.1/ODRL-DD");
_STLIT8(K6, "http://www.w3.org/2000/09/xmldsig/");

// Intermediate
const void * const KStringPointers[] =
    {
    (const void*)&K1,
    (const void*)&K2,
    (const void*)&K3,
    (const void*)&K4,
    (const void*)&K5,
    (const void*)&K6
    };

const TStringTable DrmRel1_0StringDict00AttributeValueTable::Table = {6, KStringPointers, ETrue};
